# 网络请求设置
request:
  timeout: 10 # 超时设置
  ssl: false # ssl设置

# 要抓取的 issues 配置
issues:
  repo: ymxblog/friends # 仓库持有者/仓库名
  label:
  groups: ['active','checklist','suspend','404','花架','花友','花族','花主']
  sort: updated-aesc
