name: 友链模板
description: 自助添加友链。
labels: []
body:
  - type: markdown
    id: readme
    attributes:
      value: |
        ## 填写说明
        欢迎自助申请本站友链，**星号(*)为必填项**。审核通过后会实时同步到博客，感谢理解，期待与您成为朋友！如果有任何不便，敬请包涵。
        > 申请前请先添加本站友链，谢谢！
         本站友链信息如下：
         ```yaml
           -  name: 叶泯希
              link: https://blog.418121.xyz/
              avatar: https://blog.418121.xyz/images/avatar.webp 
              descr: 意义是自己赐予的
              rss: https://blog.418121.xyz/feed.xml
              linkpage: https://blog.418121.xyz/links/
              
              博客名称：叶泯希
              博客地址：https://blog.418121.xyz/
              博客头像：https://blog.418121.xyz/images/avatar.webp
              博客描述：意义是自己赐予的
              订阅地址：https://blog.418121.xyz/feed.xml
              友链地址：https://blog.418121.xyz/links/
         ```
         ![友链填写示例](https://raw.githubusercontent.com/ymxblog/friends/refs/heads/main/.github/ISSUE_TEMPLATE/1.webp)
  - type: checkboxes
    id: checks
    attributes:
      label: 申请友链要求如下
      description: 请认真检查以下当中的每一项，并在相符的项前打勾。
      options:
        - required: true
          label: 非营利性、无商业广告、无木马植入，不违反中华人民共和国网络安全法。
        - required: false
          label: 需要安全连接HTTPS，不需备案，有自己的域名（包括*.github.io等二级域名）。
        - required: false
          label: 建站需半年或有十篇原创文章以上，仅限博客，类型不限，内容积极向上，保持更新。
        - required: false
          label: 无违反国家相关法律法规和道德底线的内容，不涉反动言论和政治敏感话题，不传播色情淫秽，邪教组织等内容。
        - required: false
          label: 申请前请确保贵站已经添加本站。
        - required: false
          label: 看我心情。
  - type: textarea
    id: config-file
    validations:
      required: true
    attributes:
      label: 友链信息
      description: 前四需要项必填，第五项选填，第六、七项由作者填写，最后两项请填入友链地址和订阅地址请在双引号中填写，不要修改格式。
      value: |
        ```json
        {
            "title": "",
            "link": "",
            "avatar": "",
            "descr": "",
            "topimg": "",
            "tag": "",
            "color": "",
            "rss": "",
            "linkpage": ""
        }
        ```
  - type: input
    id: friends-repo
    attributes:
      label: 友链仓库（可选）
      description: 如果您使用 issue 作为友链源，请附上 issue 仓库链接。
      placeholder: "如: https://github.com/ymxblog/friends/"
