name: 自动获取友链更新
on:
  push:
    branches:
      - output

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v4
        with:
          ref: output
      
      - name: 检查v2文件夹是否被更改了
        id: check_changes
        run: |
          # 检查 links 文件夹中的文件是否被更改
          if [ "$(git diff --name-only HEAD^ HEAD | grep '^v2/')" ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
      
      - name: Trigger another repository action
        if: env.changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: yeminxi/solitude  # 替换为目标仓库
          token: ${{ secrets.MY_SECRET_TOKEN }}  # 使用之前设置的 PAT
          event-type: repo-changed  # 自定义事件类型
