name: Trigger Private Repo B
on:
  push:
    branches: [output]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MY_SECRET_TOKEN }}  # 必须为账号B的PAT
          repository: yeminxi/hexo_code
          event-type: repo-changed
          # 添加私有仓库专属参数
          content-type: json
          client-payload: '{"private": true, "branch": "output"}'

