name: 检测 Issue 事件

on:
  issues:
    types:
      - opened     # 当创建新的 issue 时
      - edited     # 当编辑现有 issue 时
      - reopened    # 当重新打开之前关闭的 issue 时
      - closed      # 当关闭 issue 时

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Trigger another repository action
        if: env.changed == 'true' && env.source_valid == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: yeminxi/solitude  # 目标仓库
          token: ${{ secrets.MY_SECRET_TOKEN }}  # 使用前面设置的 PAT
          event-type: repo-changed  # 事件类型
