name: Generator

on:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Update links #更新
      run: |
        python generator/main.py
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'output'
        force-push: 'true'
        commit-message: 'Generate Json'
        name: github-actions[bot]
        email: github-actions[bot]@noreply.github.com
    - name: Trigger another repository action
      uses: peter-evans/repository-dispatch@v3
      with:
        repository: yeminxi/hexo_code  # 替换为第二个账号的目标仓库
        token: ${{ secrets.MY_SECRET_TOKEN }}  # 使用之前设置的 PAT
        event-type: repo-changed  # 自定义事件类型

