name: Generator

on:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Update links #更新
      run: |
        python generator/main.py
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ef: output  # 切换到 output 分支
    
    - name: Generate Files
      run: |
        echo "New content" > generated.json
    
    - name: Commit & Push (Native)
      env:
        REPO_TOKEN: ${{ secrets.PAT }}
      run: |
        git config user.name "ymxblog"
        git config user.email "ymxblog@qq.com"
        git add .
        git commit -m "Generate Json"
        git push "https://x-access-token:${PAT}@github.com/${{ github.repository }}.git" HEAD:output --force

