name: 获取新的友链

on:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 克隆至Github Action 路径
      uses: actions/checkout@v4
    - name: 使用指定python版本
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: 安装依赖 #安装requests
      run: |
        pip install -r requirements.txt
    - name: 更新友链 #更新
      run: |
        python generator/main.py
    - name: 推送本仓库分支output
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.PAT }}
        push-branch: 'output'
        force-push: 'true'
        commit-message: 'Generate Json'
        name: ${{ secrets.GITHUBUSERNAME }}
        email: ${{ secrets.GITHUBEMAIL }}
    - name: 推送至CDN仓库
      run: |
        cd ./
        git init
        git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
        git config --global user.email "${{ secrets.GITHUBEMAIL }}"
        git branch -M main
        git add v2 # 仅添加特定的文件或目录
        git commit -m "友链更新" || echo "No changes to commit"
        git remote add origin https://${{ secrets.GITHUBUSERNAME }}:${{ secrets.PAT }}@github.com/${{ secrets.GITHUBUSERNAME }}/CDN.git
        git pull origin main --rebase
        git push -u origin main

    # - name: 发送请求至本仓库的另外一工作流
    #   uses: peter-evans/repository-dispatch@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN
    #     repository: ${{ github.repository }}  # 指向当前仓库
    #     event-type: linkschange
    #     client-payload: '{"branch": "output"}'
