name: Generator

on:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Update links #更新
      run: |
        python generator/main.py
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.PAT }}
        push-branch: 'output'
        force-push: 'true'
        commit-message: 'Generate Json'
        name: ${{ secrets.GITHUBUSERNAME }}
        email: ${{ secrets.GITHUBEMAIL }}
    - name: 推送至CDN仓库
      run: |
        cd ./v2
        git init
        git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
        git config --global user.email "${{ secrets.GITHUBEMAIL }}"
        git branch -M main
        git add . # 仅添加特定的文件或目录
        git commit -m "友链更新" || echo "No changes to commit"
        git remote add origin https://${{ secrets.GITHUBUSERNAME }}:${{ secrets.PAT }}@github.com/${{ secrets.GITHUBUSERNAME }}/CDN.git
        git push -u origin main

    # - name: Trigger Local Workflow
    #   uses: peter-evans/repository-dispatch@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN
    #     repository: ${{ github.repository }}  # 指向当前仓库
    #     event-type: linkschange
    #     client-payload: '{"branch": "output"}'
